# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
  - r: 3.2
    warnings_are_errors: false
  - r: 3.3
    warnings_are_errors: false
  - r: 3.4
  - r: release

after_success:
  - Rscript -e 'covr::codecov()'
